version: '3.8'

services:
  app:
    build: .
    container_name: technoheven_app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Dhaka
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload